name: SE Extended PrePatchs

on:
  workflow_dispatch:
  schedule:
    - cron: '45 11,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SETTING UP JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: SETTING JAVA_HOME
        run: echo "JAVA_HOME=$(echo ${{ steps.setup-java.outputs.java-home }})" >> $GITHUB_ENV

      - name: SETTING UP NODE.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: CHECKING OUT CODE
        uses: actions/checkout@v4

      - name: INSTALLING DEPENDENCIES
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
        shell: bash

      - name: INSTALLING UNZIP
        run: sudo apt-get install unzip -y

      - name: INSTALLING PUP
        run: |
         wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
         unzip pup.zip
         chmod +x pup
         sudo mv pup /usr/local/bin/
        working-directory: . 

      - name: GRANTING PERMISSIONS TO APK DOWNLOADER SCRIPT
        run: chmod +x downloader.sh
        working-directory: .  

      - name: RUNNING APK DOWNLOADER SCRIPT
        run: |
         ./downloader.sh

      - name: RUNNING THE JAVA COMMAND
        run: |
          java -jar lspatch.jar -m "$GITHUB_WORKSPACE/Core.apk" -f -l 2 -v snapchat.apk

      - name: RENAMING APK FILE
        run: |
          mv ./snapchat-402-lspatched.apk ./${{ env.VERSION }}-PrePatch.apk

      - name: UPLOADING APK ARTIFACT
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}-PrePatch.apk
          path: ./${{ env.VERSION }}-PrePatch.apk

      - name: DOES THE RELEASE EXIST?
        id: check_release
        run: |
          RELEASE_VERSION=${{ env.VERSION }}
          if curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_VERSION; then
            echo "Release $RELEASE_VERSION already exists."
            RELEASE_VERSION=$(echo $RELEASE_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./')
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: CREATES OR UPDATES RELEASE
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.VERSION }}-PrePatch.apk
          tag_name: ${{ env.VERSION }}